datasource: ''''''
ddl-auto: update
driver-class-name: com.mysql.jdbc.Driver
hibernate: ''''''
jpa: ''''''
password: 09182@Sql
show-sql: true
spring: ''''''
url: jdbc:mysql://localhost:3306/product_details
username: root
